### PR TITLE
When getFileList function returns null, getFileModel function returns…

### PR DESCRIPTION
**Pull request by gokaysatir**
… error.

This commit enables getFileModel function to return null safely. So the real issues that were hidden behind this error should be more visible now.

Signed-off-by: Gökay Şatır <gokaysatir@collabora.com>

* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] Sign-off message is added to all commits
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by gokaysatir** [comment]
We have a report from a user with below title.
"COOL doesn't load in Firefox"
And there are a couple of GitHub issues here & there related to this bug:

https://github.com/nextcloud/richdocuments/issues/2017
https://github.com/nextcloud/richdocuments/issues/2125

So i chased the issue and fixed a couple of things on Collabora Online. I also saw that a function wasn't working properly. This commit solves that issue.

The work i have done so far can not solve the issue itself. It only pushes the unrelated bugs out of the way.

To reproduce the initial bug that i was chasing:
* Have two or more (logged in nextcloud) users try to open the same file on Firefox.

With above steps, the bug can be almost always reproduced.

If we merge the commit of this PR, we will see no errors on JS console but the original issue will stay.

Lastly, from my notes:
"There is an error on Nextcloud "Viewer.vue" file that initiates "FilesAppIntegration.js (richdocuments)" file without the required parameters."

^This is the point i can't chase any more. @juliushaertl i'll be happy if someone can help me to find the root cause of the bug, thank you :)

**Comment by juliushaertl** [comment]
@gokaysatir I've been trying to reproduce any issue with firefox but wasn't able to see any hidden error that you mentioned in our call. Do you have any additional details on that like the exact error message or stack trace?

Steps taken can be seen in the screen recording, but this was basically two users opening the same time in FF with your patch.

https://user-images.githubusercontent.com/3404133/168336140-40580afd-72ec-4b51-aa0c-cd5a2cb553f5.mov

**Review by juliushaertl — APPROVED** [review]
Change makes sense so LGTM but would be still good to chase the other reported issue ;)

**Comment by juliushaertl** [comment]
I think this might be the additional fix needed https://github.com/nextcloud/richdocuments/pull/2212 in addition. @gokaysatir Any chance you could test if that fixes the issue for you as well?

**Comment by gokaysatir** [comment]
> I think this might be the additional fix needed #2212 in addition. @gokaysatir Any chance you could test if that fixes the issue for you as well?

Of course, let me have  a look and inform you.

**Comment by gokaysatir** [comment]
> I think this might be the additional fix needed #2212 in addition. @gokaysatir Any chance you could test if that fixes the issue for you as well?

Hello, i tried it again with & without the PR you pointed. I can confirm that it solves the issue. Hopefully my test is complete and we won't see that problem again:) Thanks for the fixes.

**Pull request merged**
