### PR TITLE
fix(client): Use shared default options for HTTP client requests

### PR DESCRIPTION
**Pull request by mejo-**
Makes sure we always set a sane timeout and `allow_local_address`.

Fixes: #3255
Fixes: #3435
Fixes: nextcloud/server#44190

### Checklist

- [x] Code is properly formatted
- [x] Sign-off message is added to all commits
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]

**Comment by juliushaertl** [comment]
@mejo- Can you take care of the manual backport for 28?

**Comment by mejo-** [comment]
Manual backport for 28: https://github.com/nextcloud/richdocuments/pull/3993

**Pull request merged**
