### PR TITLE
Improve disable certificate verification handling

### PR DESCRIPTION
**Pull request by weberhofer**
* Resolves: #948
* Target version: master 

- [x] Code is properly formatted
- [ ] Sign-off message is added to all commits
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by weberhofer** [comment]
I don't know how to sign off the code...

**Comment by mmaridev** [comment]
If you already have a key, simply run `git commit --amend -s --no-edit` .
If not, see https://help.github.com/en/github/authenticating-to-github/signing-commits

**Comment by juliushaertl** [comment]
Maybe you can squash all commits into one. After that running `git commit --amend --signoff` should do the trick. 

@mmaridev Note that the DCO is just about the sign off message added to the commit message, gpg signature is not a hard requirement.

**Comment by weberhofer** [comment]
Resubmitted with  #959, hopefully correctly signed with my new key

**Pull request closed without merging**
