### PR TITLE
Fix errors when extracting content controls

### PR DESCRIPTION
**Pull request by juliusknorr**
- **fix: properly filter for content controls**
  - This commit fixes the filtering that has been in place but was likely not working anymore due to an upstream change 
- **fix: Catch unexpected results with no type**
  - Safeguard the results to not fail hard on unexpected result sets

Fix https://github.com/nextcloud/richdocuments/issues/4228

### CODE REVIEW

**Comment by elzody** [comment]
Works fine for me 👍🏻

**Review by elzody — APPROVED** [review]

**Comment by elzody** [comment]
Not merging right away because I wasn't sure to which versions you want to backport (I assume back to stable28?)

**Comment by juliusknorr** [comment]
I think we only have that api integration in 30+

**Pull request merged**
