### PR TITLE
feat: add config option mobile_editing

### PR DESCRIPTION
**Pull request by luka-nextcloud**
* Resolves: https://support.nextcloud.com/#ticket/zoom/49745
* Target version: main

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] Sign-off message is added to all commits
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]

**Comment by jakobroehrl** [comment]
@juliushaertl @luka-nextcloud 
Good morning, 
where can I configure this?
Some of my smartphones already can't open the mobile documents.
Could it be that it is disabled by default?
Thanks

**Comment by jakobroehrl** [comment]
@juliushaertl @luka-nextcloud
Tested a downgrade to 8.1.1. now it works again with the mobile apps.
So it must be this PR.

**Pull request merged**
