### PR TITLE
Use private field for sharing Zotero key

### PR DESCRIPTION
**Pull request by eszkadev**
Merge after: https://github.com/CollaboraOnline/online/pull/5651
Merge together with: https://github.com/CollaboraOnline/online/pull/5652

This uses private data to store Zotero key (not shared with others)

### CODE REVIEW

**Review by juliushaertl — COMMENTED** [review]
Code looks good. Waiting with the merge for the upstream PRs.

**Review by lpranam — APPROVED** [review]

**Comment by timar** [comment]
@eszkadev can you please fix the typo in commit message? `filed`
Then this can be merged, because the upstream patch has been merged.

**Comment by eszkadev** [comment]
@juliushaertl it's ready to merge, I will merge after that Online part

**Review by juliushaertl — APPROVED** [review]

**Pull request merged**
