### PR TITLE
Properly obtain original source file for public share links

### PR DESCRIPTION
**Pull request by juliushaertl**
* Resolves: #622 
* Target version: master 

### Summary
- Move to database migrations
- Store share token with wopi token entry
  With this we are now able to properly obtain the correct file source if a logged-in user is opening a public share link

### CODE REVIEW

**Comment by juliushaertl** [comment]
Integration tests need to be adjusted since the wopi token is not generated anymore without a guest name in 28c7dfd

**Comment by juliushaertl** [comment]
@rullzer Reviews and testing would be highly appreciated :wink:

**Comment by vpecinka** [comment]
thanks!

**Pull request merged**
