### PR TITLE
Refactor post message handling

### PR DESCRIPTION
**Pull request by juliushaertl**
Required for #539 
Includes #552

- [x] Extract incoming post message handling
- [x] Make sure the file is always created and added to the files list before passing it to the document handling. This way we can obmit the expensive reloading of the file list
- [x] Replace parent calls with dedicated post messages
  - [x] Collabora post messages are passed though to the viewer
- [x] Move Nextcloud files integration to the top frame
  - [x] Avatar list
  - [x] File actions
  - [x] File list updates
  - [x] Insert image from Nextcloud
  - [x] Share action opens sidebar
  - [x] SaveAs
  - [x] Rename
  - [x] Version sidebar
    - [x] Preview of versions
    - [x] Set proper timestamp for last saved version
    - [x] Restore

## QA matrix for post message involved features

| Feature | Web | Android |
| ------- | :---: | :-------: |
| Document loading (logged in) | ✔ | ➖ |
| Document loading (direct API) | ➖ | ✔ |
| Document loading (public share file) | ✔ | ➖ |
| Document loading (public share folder) | ✔  | ➖ |
| Avatar list | ✔ | ➖ | 
| File actions | ✔ | ➖ |
| Insert image from Nextcloud | ✔ | ✔ |
| Insert image from local | ✔ | ✔ |
| Share | ✔ | ✔ |
| Close | ✔ | ✔ |
| SaveAs | ✔ | ➖ |
| Rename | ✔ | ➖ |
| Share after rename | ✔ | ✔ |
| Show versions | ✔ | ➖ |
| Preview of versions | ✔ | ➖ |
| Restore version | ✔ | ➖ |
| Download | ✔ | ✔ |
| Print | ✔ | ✔ |

➖ not available

### CODE REVIEW

**Comment by juliushaertl** [comment]
@tobiasKaminsky Since you also have a local collabora setup, maybe you can give this a test run as well? :wink:

**Comment by tobiasKaminsky** [comment]
I gave it a some test with Collabora, inserted local/remote image, opened document.
Looks good so far :-)

**Comment by rullzer** [comment]
It opens on android for me. But sharing is disabled.

**Comment by juliushaertl** [comment]
@rullzer As discussed this is most likely a bug in Collabora when sharing is only possible after you enter the edit mode.

**Comment by rullzer** [comment]
Right seems so indeed. Lets dpo this then

**Pull request merged**
