### PR TITLE
Add avatar to UserExtraInfo

### PR DESCRIPTION
**Pull request by LukasReschke**
Will require master of Nextcloud (aka 13) and https://github.com/nextcloud/server/pull/6813 merged.

Signed-off-by: Lukas Reschke <lukas@statuscode.ch>

### CODE REVIEW

**Comment by LukasReschke** [comment]
screen shot 2017-10-11 at 15 26 45
screen shot 2017-10-11 at 15 28 50

**Comment by timar** [comment]
Thanks for this @LukasReschke ! Does that mean that we need to make a branch for nc12 before we merge this patch?

**Comment by LukasReschke** [comment]
In addition, I'll work on the following change in the server to always return a proper avatar: https://github.com/nextcloud/server/issues/5750

**Comment by LukasReschke** [comment]
> Thanks for this @LukasReschke ! Does that mean that we need to make a branch for nc12 before we merge this patch?

Sadly, this feature will only properly work with Nextcloud 13 due to https://github.com/nextcloud/server/issues/5750 and https://github.com/nextcloud/server/pull/6813 being required.

I can add a if block around it to include the user extra info only if we're on >= 13. That should work around the problems here.

Objections? :-)

**Comment by timar** [comment]
`

> I can add a if block around it to include the user extra info only if we're on >= 13. That should work around the problems here.

That would be great, thanks.

**Comment by rullzer** [comment]
https://github.com/nextcloud/server/pull/6813 is merged

**Comment by LukasReschke** [comment]
@timar Done.

**Pull request merged**
