### PR TITLE
convert nextcloud locale to BCP47 languages tag correctly

### PR DESCRIPTION
**Pull request by leejoneshane**
tested out!

### CODE REVIEW

**Comment by juliushaertl** [comment]
Thanks a lot for your pull request, can you describe a bit more in detail where there was an issue with the code?

**Comment by juliushaertl** [comment]
cc @eszkadev Maybe that is something to be fixed on your side as well?

**Comment by eszkadev** [comment]
Thanks for notification, modification indicator needed some tweak

**Comment by rullzer** [comment]
Lets do this then

**Pull request merged**
