### PR TITLE
option to use new grouped saveas

### PR DESCRIPTION
**Pull request by pedropintosilva**
COOL can now provide extensions for different
file types such as odt to docx etc. without needing to type it manually.

Signed-off-by: Mert Tumer <mert.tumer@collabora.com>

* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] Sign-off message is added to all commits
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by pedropintosilva** [comment]
@juliushaertl the Online counterpart already merged : https://github.com/CollaboraOnline/online/pull/5252 and it seems this richdocuments  commits were forgotten (cc: @merttumer @timar @eszkadev )

**Comment by juliushaertl** [comment]
Thanks for that @pedropintosilva ❤️

**Review by juliushaertl — APPROVED** [review]

**Comment by pedropintosilva** [comment]
Actually when I tested (it was in some not so recent version of richdocument) I have tried to test it again via 25stable and I'm not able..

So I have pulled latest NC docker, removed richdocuments, git clone , checkout 25stable (just to be sure the commit is there) and I'm not able to see it... I'm not sure if anything changed. However, I'm able to see it if
1. File -> Properties 
2. Set password
3. Password dialog: type apss
4. Save
5. Close
6. Open the same file
7. Go to file

image
 and in compact mode
image

**Comment by pedropintosilva** [comment]
@juliushaertl maybe because `saveAsMode` is not set initially (?)

**Comment by pedropintosilva** [comment]
and then after https://github.com/nextcloud/richdocuments/pull/2551#issuecomment-1289105699 I'm not able to reproduce the bug again, even with a newly created user and new document

**Comment by pedropintosilva** [comment]
I just remove richdocuments, pulled again ... and it works now...

```bash
rm -rf richdocuments/
git clone https://github.com/nextcloud/richdocuments.git
cd richdocuments/
git checkout 25stable
npm ci
npm run dev
```
:man_shrugging: I don't understand

**Comment by pedropintosilva** [comment]
Aha! @eszkadev alluded tot he fact that maybe it was simply cache that NC caching for some properties and it is possible that it was updated at some point and started to work, but before it was using old values

**Pull request merged**
