### PR TITLE
fix: Use proper file id for direct editing

### PR DESCRIPTION
**Pull request by juliusknorr**
As reported by @marinofaggiana there was an issue creating new files on iOS which I could reproduce with curl.

I assume this broke with some refactoring, but not sure where, requiring a test to avoid future regressions

Still to do:
- [ ] Test with iOS/Android
- [x] I think we should have tests for this, double check or add

### CODE REVIEW

**Comment by juliusknorr** [comment]
Added a cypress test for this

**Comment by juliusknorr** [comment]
@elzody I fail to validate this locally on iOS/Android due to issues with my build environments with that. I'd vote to review and merge, then we can test on the daily instance with real devices and we can backport once double checked.

**Review by elzody — APPROVED** [review]

**Comment by juliusknorr** [comment]
All right, seems something is still odd, when testing on iOS i end up with 0kb files. Need to figure out what is different there compared to the cypress tests.

**Pull request merged**
