### PR TITLE
Hide close button on single file shares that have hide download enabled

### PR DESCRIPTION
**Pull request by sharonwuu**
* Resolves: https://github.com/nextcloud/richdocuments/issues/2585
* Target version: main

### Checklist

- [X] Code is properly formatted
- [X] Sign-off message is added to all commits
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by juliushaertl** [comment]
@sharonwuu could you rebase your pull request again to latest main branch? This should make sure that the cypress tests run now.

**Comment by sharonwuu** [comment]
I've rebased my pull request to the latest main branch. Thanks for the review.  :)

**Comment by juliushaertl** [comment]
Thanks for your contribution :)

**Pull request merged**
