### PR TITLE
fix: Uncheck group limit in admin settings

### PR DESCRIPTION
**Pull request by elzody**
* Resolves: #3506 
* Target version: main

### Summary
Previously, trying to uncheck the checkbox would simply re-enable it automatically. This PR fixes this issue. Also adds an `inputLabel` prop to the `NcSelect` so it doesn't error anymore (and accessibility reasons :D)

https://github.com/nextcloud/richdocuments/assets/23369449/3940d131-83a1-49e3-a8b3-af656070c70a

### Checklist

- [x] Code is properly formatted
- [x] Sign-off message is added to all commits
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by juliushaertl** [comment]
Thanks for looking into this. We used to hide the select if the box was unchecked. Maybe we can bring back this behaviour as well?

**Review by jancborchardt — COMMENTED** [review]
Looks good, have only the same feedback as Julius about hiding the dropdown. :)

**Review by juliushaertl — APPROVED** [review]

**Pull request merged**
