### PR TITLE
Make files_versions work again

### PR DESCRIPTION
**Pull request by michag86**
Fix for #9
Added some lines which were lost after rewrite with version 1.1.22.

@MorrisJobke: this only fixes files_version. Revision History is still not working.

### CODE REVIEW

**Comment by pieter-groeneweg** [comment]
I manually made the change to the file, versioning in NextCloud11 works but the versioning does not show in version history in Collabora CODE

**Comment by MorrisJobke** [comment]
cc @LukasReschke @icewind1991 @rullzer @nickvergessen

**Comment by nickvergessen** [comment]
Does this also fix activities? I saw that they were not triggered before.

**Comment by michag86** [comment]
@nickvergessen activity is added on save, but it is looking like this:

grafik

**Comment by pranavk** [comment]
I notice an exception when trying to save the file with above mentioned fix in the nextcloud logs.

```
{"reqId":"WNOZFQBU5lwflp3Np5UujgAAAAg","remoteAddr":"127.0.0.1","app":"no app in context","message":"Exception: {"Exception":"InvalidArgumentException","Message":"The given author user is invalidN;","Code":0,"Trace":"#0 /srv/nc/apps/activity/lib/FilesHooks.php(889): OC\\Activity\\Event->setAuthor(NULL)\n#1 /srv/nc/apps/activity/lib/FilesHooks.php(182): OCA\\Activity\\FilesHooks->addNotificationsForUser('test', 'changed_by', Array, 76, '/test.odt', true, true, 0, 'file_changed')\n#2 /srv/nc/apps/activity/lib/FilesHooks.php(122): OCA\\Activity\\FilesHooks->addNotificationsForFileAction('/test.odt', 'file_changed', 'changed_self', 'changed_by')\n#3 /srv/nc/apps/activity/lib/FilesHooksStatic.php(53): OCA\\Activity\\FilesHooks->fileUpdate('/test.odt')\n#4 /srv/nc/lib/private/legacy/hook.php(106): OCA\\Activity\\FilesHooksStatic::fileUpdate(Array)\n#5 /srv/nc/lib/private/Files/View.php(614): OC_Hook::emit('OC_Filesystem', 'post_update', Array)\n#6 /srv/nc/lib/private/Files/View.php(663): OC\\Files\\View->emit_file_hooks_post(true, '/admin/files/te...')\n#7 /srv/nc/lib/private/Files/Node/File.php(54): OC\\Files\\View->file_put_contents('/admin/files/te...', Resource id #549)\n#8 /srv/nc/apps/richdocuments/lib/Controller/WopiController.php(192): OC\\Files\\Node\\File->putContent(Resource id #549)\n#9 [internal function]: OCA\\Richdocuments\\Controller\\WopiController->putFile('76', 'SU3uy26qvaPUfT8...')\n#10 /srv/nc/lib/private/AppFramework/Http/Dispatcher.php(160): call_user_func_array(Array, Array)\n#11 /srv/nc/lib/private/AppFramework/Http/Dispatcher.php(90): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Richdocuments\\Controller\\WopiController), 'putFile')\n#12 /srv/nc/lib/private/AppFramework/App.php(114): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Richdocuments\\Controller\\WopiController), 'putFile')\n#13 /srv/nc/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\\AppFramework\\App::main('OCA\\\\Richdocumen...', 'putFile', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#14 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#15 /srv/nc/lib/private/Route/Router.php(299): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#16 /srv/nc/lib/base.php(1010): OC\\Route\\Router->match('/apps/richdocum...')\n#17 /srv/nc/index.php(40): OC::handleRequest()\n#18 {main}","File":"/srv/nc/lib/private/Activity/Event.php","Line":165}","level":3,"time":"2017-03-23T09:44:53+00:00","method":"POST","url":"/nextcloud/index.php/apps/richdocuments/wopi/files/76_oc4zrq3339pu/contents?access_token=SU3uy26qvaPUfT8CSNhK3jqn8xG3bdb6&access_token_ttl=0&permission=edit","user":"--","version":"11.0.0.10"}
```

Sorry for obfuscated logs.

Nevertheless, the above fix seems to work and stores the revisions of the file.

Regarding, revisions not showing up in the revision history sidebar, here's a quick fix that works -
#33

**Comment by mpiscaer** [comment]
I used https://github.com/nextcloud/richdocuments/pull/27 and https://github.com/nextcloud/richdocuments/pull/33 patches.

This fixes

- the "versions" in NC.
- The "revision history" in CODE

This does not fix
- the issue when I want to view an specific version in CODE.
- The activities like mentioned by: michag86

Please see the screencast "Activities_and_view_revisions.avi" for both issues. Do I need to create a two new issue for both issues?
Screencast: https://share.piscaer.com/index.php/s/F4BmIyZU5GOWyZU The password is: This_is_the_public_passw0rd

**Comment by irule311** [comment]
So #27 and #33 do fix the revision history saving, however, the preview for the revisions do not work. It shows the most recent version when selecting a previous version. Only when restoring the previous version of the document are you able to actually preview the document.

**Comment by pranavk** [comment]
@irule311 #50 fixes it for me.

**Comment by irule311** [comment]
@pranavk #50 doesn't seem to fix it for me. I get "Well, this is embarrassing, we cannot connect to your document. Please try again." Its possible because I'm still on NC 11?

**Comment by pranavk** [comment]
I worked on top of master which has 12 as minimum NC version required; didn't try applying this patch on NC11 (yet)

**Comment by irule311** [comment]
So I just updated to NC 12 and tried #50 but it appears as though all versioning disappeared. With the latest master on NC 12, the versioning was there but the history didn't change in the previews.

**Comment by masterdot** [comment]
Hey there,
I did stumble upon this issue with our nextcloud aio instance. 
Is this already fixed? I did discover this issue today with a .odt file. There were no versions made, but i could find some versions, but only a few in the activities. 
I would have expected versions of all files editable files in nextcloud.
If there is a (quick)fix, thanks in advance :)

**Comment by nickvergessen** [comment]
It's fixed since 7 years, yes.
If you have an issue please create a new ticket instead.

**Comment by masterdot** [comment]
The problem does still exist, but is only happening in Group folders.
https://github.com/nextcloud/groupfolders/issues/2718

**Pull request merged**
