### PR TITLE
feat: Add parameter to allow converting files after filling out fields

### PR DESCRIPTION
**Pull request by juliushaertl**
Need to review my own code again tomorrow but so far this should do the trick to help the integrations team with building nice workflows

cc @julien-nc 

I should also add a test

```
curl -v -X POST -H 'OCS-APIRequest: 1' -u admin:admin https://nextcloud.local/ocs/v2.php/apps/richdocuments/api/v1/template/fields/fill/406\?convert\=pdf  > test2.pdf
curl -v -X POST -H 'OCS-APIRequest: 1' -u admin:admin https://nextcloud.local/ocs/v2.php/apps/richdocuments/api/v1/template/fields/fill/406\?convert\=pdf\&destination\=myfile.pdf
```

### CODE REVIEW

**Review by julien-nc — APPROVED** [review]
Tested locally, works like a charm.
Code looks good.
Nice that it now prints the document content if destination is null!
Thanks a lot :blue_heart:

**Comment by juliushaertl** [comment]
Pushed some integration tests for the endpoints

**Review by elzody — APPROVED** [review]
Gave it a thorough test, works nicely. Also nice code

**Pull request merged**
