### PR TITLE
Always enable editing for admins

### PR DESCRIPTION
**Pull request by juliushaertl**
Make sure that admins always can work with Collabora to avoid breaking settings

### CODE REVIEW

**Review by eneiluj — APPROVED** [review]
Funny to think of admins locking themselves out.
:+1: 

Wouldn't it make sense to check `isAdmin` before the `use_groups` config value? I don't know which is more costly between `isAdmin` and `config->getAppValue`...

**Comment by juliushaertl** [comment]
Shouldn't matter much in terms of performance, especially since the admin check is probably the edge case ;)

**Pull request merged**
