### PR TITLE
Add tablet parm for Insert_Button

### PR DESCRIPTION
**Pull request by Darshan-upadhyay1110**
* Resolves: #
* Target version: main

### Summary
Remove Open_Local_Editor insert button for tablet view

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] Sign-off message is added to all commits
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]

**Comment by pedropintosilva** [comment]
related Collabora Online PR merged https://github.com/CollaboraOnline/online/pull/7005

**Comment by pedropintosilva** [comment]
@juliushaertl  some tests failed but seem completely unrelated to this change

**Review by juliushaertl — APPROVED** [review]

**Pull request merged**
