### PR TITLE
Be fair about compatiblity of this module

### PR DESCRIPTION
**Pull request by mmaridev**
### Checklist

- [ X] Code is properly formatted
- [ X] Sign-off message is added to all commits
- [ X] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by juliushaertl** [comment]
I cannot tell anything about general WOPI compatibility as from my side this is only tested with Collabora Online. I also think that we have quite some code in place that is not part of the official WOPI spec, like the capabilities, so I would prefer to keep this for Collabora specific.

See https://github.com/nextcloud/richdocuments/issues/639 for some past comment on the branding.

cc @timar

**Comment by mmaridev** [comment]
Sorry, what infos are needed?

**Comment by juliushaertl** [comment]
Well I'm against advertising some compatibility that is not really tested either by Nextcloud or Collabora, that is why I was pinging @timar what his point on this is as there has been discussions about the naming in the past.

**Comment by gary-kim** [comment]
I think it could be nice to have a message in the README that the app may be compatible with other WOPI editors but make it clear that Collabora Online is the only one that is tested. Don't think it's necessary to remove the current refernces to Collabora Online. How about just adding a message like `**This app may work with other WOPI Edtiors such as LibreOffice Online but it is not tested.**`?

I also actively use LibreOffice Online rather than Collabora Online but it's not clear that a setup like this would work if someone is looking at the README.

**Comment by juliushaertl** [comment]
What @gary-kim suggests sounds good to me. Mind to address that @mmaridev ?

**Comment by mmaridev** [comment]
Looks good to me

Il Lun 8 Giu 2020, 19:58 Julius Härtl <notifications@github.com> ha scritto:

**Comment by gary-kim** [comment]
@mmaridev Mind if I take over this PR? 

I just had some fun compiling LOOL from scratch and it reminded me of this :)
image

**Comment by mmaridev** [comment]
You're more than welcome. (You need me to do something here in GitHub to let you work?)

**Comment by gary-kim** [comment]
As long as `Allow edits by maintainers` is on, should be fine!

**Comment by juliushaertl** [comment]
Any update?

**Comment by mmaridev** [comment]
@gary-kim if you need any help just let me now

**Comment by gary-kim** [comment]
Slipped my mind

**Comment by kendy** [comment]
Closing, this is pending decision by TDF on LibreOffice Online's future. Can reopen later if necessary.

**Comment by gary-kim** [comment]
We're just adding a one sentence message about potential compatibility with other WOPI compatible editors, not actually renaming it.

**Review by juliushaertl — APPROVED** [review]

**Pull request merged**
