### PR TITLE
fix: emit allow attribute on all iframes for the clipboard (related t…

### PR DESCRIPTION
**Pull request by vmiklos**
…o #3474)

The unhandled cases were:

- read-only view

- view a past revision

- for completeness, also adapt the iframe in files.js

### CODE REVIEW

**Comment by vmiklos** [comment]
@juliushaertl could you please review this? Thanks.

This adds the 'allow' attribute at the remaining places. I'm not sure what the files.js case is about, so I just did that for completeness. If you have a guess, I would be happy to learn. :-)

Other than that, please also merge the PR if you approve, I'm not a maintainer in this repo.

**Comment by juliushaertl** [comment]
> This adds the 'allow' attribute at the remaining places. I'm not sure what the files.js case is about, so I just did that for completeness. If you have a guess, I would be happy to learn. :-)

That is still some legacy code as the public share links of files are not migrated to Vue.js yet, so we have two different implementations for launching the iframe. Hopefully gets obsolete at some point and can just use Viewer.vue

**Review by juliushaertl — APPROVED** [review]

**Pull request merged**
