### PR TITLE
Fix editing publicly shared documents

### PR DESCRIPTION
**Pull request by andyboeh**
This fixes editing of documents in publicly shared subfolders (#12 and #103).

### CODE REVIEW

**Comment by pranavk** [comment]
It confuses me why we are passing fileName at all in case of public pages. The fileId is available in case of publicPages too and we can easily get the node from the fileId like this -- $node->getById($fileId)[0].

**Comment by andyboeh** [comment]
@pranavk It confused me as well, given the fact that the file ID can be retrieved in the JavaScript code easily as well. I wanted a quick solution, so I came up with this.

**Comment by pranavk** [comment]
Unless @LukasReschke sees anything fishy there, I would use the fileId there instead of fileNames. I tried the fileId approach on local and it works fine.

**Comment by pranavk** [comment]
Can you update the PR to use fileIDs instead of fileNames, please ? Let's keep it consistent.

**Comment by andyboeh** [comment]
Sorry, currently I'm too busy with other work. Maybe I'll have the time to do that in a few weeks.

**Comment by wscheicher** [comment]
For now i use this fix, looks good so far.
Thanks a lot andyboeh!

**Comment by pranavk** [comment]
Follow-up 

https://github.com/nextcloud/richdocuments/commit/e9f9711421ed1eba9cdb3b787b1a49eaed7373d1

**Comment by pranavk** [comment]
Thanks andyboeh for working on it  !

**Pull request merged**
