### PR TITLE
Move to single viewer css file

### PR DESCRIPTION
**Pull request by juliushaertl**
Saves one request

### CODE REVIEW

**Comment by thebearon** [comment]
Please note that this change caused a regression, when clicking the "+" in the file list to create a new file, the document/spreadsheet/presentation icons aren't shown anymore.

**Comment by juliushaertl** [comment]
> Please note that this change caused a regression, when clicking the "+" in the file list to create a new file, the document/spreadsheet/presentation icons aren't shown anymore.

I cannot reproduce that, maybe it is an issue with your browser caching the old file, because we didn't do the app version bumb yet on master.

**Comment by thebearon** [comment]
> I cannot reproduce that, maybe it is an issue with your browser caching the old file, because we didn't do the app version bumb yet on master.

I checked in more detail, the problem is that the CSS file was moved a level up, but the following URLs inside weren't updated:
- background-image: url('../../../../core/img/filetypes/x-office-document.svg')
- background-image: url('../../../../core/img/filetypes/x-office-spreadsheet.svg');
- background-image: url('../../../../core/img/filetypes/x-office-presentation.svg');

And yes, the bug still occurs with a freshly pulled master.

**Comment by juliushaertl** [comment]
Ah I guess you have installed Nextcloud in a subdirectory, that explains why I was not seeing any issues there, as with Nextcloud in the webserver root, the path resolves just fine. Fix incoming.

**Comment by thebearon** [comment]
Thank you!

**Pull request merged**
