### PR TITLE
Send file path to the client also, fix revision history

### PR DESCRIPTION
**Pull request by pranavk**

### CODE REVIEW

**Comment by pranavk** [comment]
This needs #27

**Comment by MorrisJobke** [comment]
cc @nickvergessen @LukasReschke @icewind1991

**Comment by MorrisJobke** [comment]
> This needs #27

@pranavk Could you rebase this branch, because #27 was merged.

**Comment by michag86** [comment]
I've tried this changes with NC 11.0.2 and richdocuments 1.1.25 with changes from #27 applied.
Revision History is shown correct, but when I select a revision, I always get the content of the latest revision. When I download the Version from version dialog, the content is correct.

**Pull request merged**
