### PR TITLE
Add option to disable certificate validation

### PR DESCRIPTION
**Pull request by kesselb**
* Resolves: #264
* Target version: master 

### Summary

image

Add option to disable certificate validation for internal nextcloud <-> collabora connections. Useful if you use self signed certificates or your collabora certificate is not trusted by your nextcloud server.

### TODO

- [ ] Test with Nextcloud 13 (don't have a running test setup)

### Checklist

- [x] Code is properly formatted
- [x] Sign-off message is added to all commits
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by juliushaertl** [comment]
Fine by me :+1:

**Comment by rullzer** [comment]
I do not fully get the reasoning here... if your collabora has an invalid certificate then also your browser will complain...

**Comment by kesselb** [comment]
> if your collabora has an invalid certificate then also your browser will complain...

Of course but you have to choice to ignore the warning. Before this pull request there is no way to accept a self signed certificate.

**Comment by rullzer** [comment]
ok fine by me then

**Comment by kevdogg** [comment]
This fix does not fix the guzzlehttp name already in use error. I wish people would quit referencing this as a fix for this problem

**Pull request merged**
