### PR TITLE
Start with new template creation mechanism

### PR DESCRIPTION
**Pull request by juliushaertl**
This pull request implements a new template creation mechanism, that will hand over an URL in the TemplateSource entry of CheckFileInfo. If present the file will be downloaded by Collabora during the document creation.

- [X] WOPI endpoint to fetch the template file
- [X] Check for hasTemplateSource capability
- [x] Provide TemplateSource in CheckFileInfo
- [x] Create token with TemplateSource when creating new documents from the web UI
- [x] Create token with TemplateSource when creating new documents from the direct editing API

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Is there any change needed on client side?

**Comment by juliushaertl** [comment]
> Is there any change needed on client side?

No, this just changes the way Nextcloud and Collabora handle creating the new file.

**Comment by tobiasKaminsky** [comment]
Stale bot on PR…?!

**Comment by juliushaertl** [comment]
Yes, doesn't matter much if the pr is open or closed for stale pull requests, as you can always reopen it :wink:

**Comment by hcvcastro** [comment]
Hi,

I am testing the patch and it works on my side with the master branch in Collabora Online.
Can you please resolve the conflicts (I did locally ), so I can merge the patch?

Thanks

**Comment by juliushaertl** [comment]
@hcvcastro seems we pushed a rebased version almost at the same time, let's continue here since I also added the direct editing. I'll do some more testing in federated sharing scenarios tomorrow but ready to merge otherwise.

**Comment by juliushaertl** [comment]
CI failures related to server php version bump. I'll fix that in a separate PR.

**Pull request merged**
