### PR TITLE
[stable30] Digitally sign documents via software certificates

### PR DESCRIPTION
**Pull request by vmiklos**
* Resolves: https://github.com/nextcloud/richdocuments/issues/4123
* Target version: stable30

### Summary

This is a backport to Nextcloud 30, seeing that effectively the original PR just added 3 new settings, so hopefully no need to wait till Nextcloud 31.

### CODE REVIEW

**Comment by vmiklos** [comment]
@elzody could you please review this? Thanks.

I got no conflicts while backporting, FWIW.

**Comment by elzody** [comment]
@vmiklos thanks i'll take a look today, sorry for being slow on this!

**Comment by elzody** [comment]
@vmiklos Since this is a feature, normally we would not backport features and they'd just be included in the next release. Is this something really needed from the Collabora side in NC 30 or can it wait for 31, or was Julius already expecting it to be backported as well? He's out sick so unfortunately have not been able to reach him yet about it.

**Comment by pedropintosilva** [comment]
@elzody we would like to really have this backported if we can : )

**Comment by vmiklos** [comment]
Thanks for the review! :-)

**Pull request merged**
