### PR TITLE
Properly check proxy status

### LINKED ISSUE #1895: v5.0.0 don't work with Collabora
**Describe the bug**
When using Collabora Built-in CODE server, we obtain infinite loading screen.

**To Reproduce**
1. Install built-in CODE serveur
2. Install or upgrade Collabora/Nextcloud Office Plugin
3. Check Nextcloud Office is using built-in CODE server and connection is OK
4. Try to open an Open Document file

**Expected behavior**
Office document to be opened and editable

**Client details:**
 - OS: Debian Bulleyes
 - Browser Firefox
 - Version 78.15.0esr
 - Device: desktop

## Server details

**Operating system**: Debian Bullseye

**Web server:** Apache

**Database:** External PGSQL

**PHP version:** 7.4.25

**Nextcloud version:** 23

**Version of the richdocuments app** 5.0.0

**Version of Collabora Online** 21.2 (same behaviour with the older version=

<details>
Revert to version 4.1.2 fixes the problem, even if marked as unsupported by Nextcloud 23.
</details>

### PR DESCRIPTION
**Pull request by juliushaertl**
Make sure that the built-in code server works properly with richdocument 5.x

Should fix #1895 #1886 when using the built-in code server

### CODE REVIEW

**Review by luka-nextcloud — APPROVED** [review]

**Review by eneiluj — APPROVED** [review]
Oh, it was written for a very old version of Axios.

**Comment by eneiluj** [comment]
@juliushaertl Should we create the stable5 banch?
On which branch should we base it?
Should it follow master for now?
Maybe it makes more sense to wait for a v6.x.x release to create the stable5 branch? :grin:

**Comment by juliushaertl** [comment]
mixed it up, i wanted to stick with major nextcloud versions now.

**Pull request merged**
