### PR TITLE
[stable28] chore(deps): update @nextcloud dependencies

### PR DESCRIPTION
**Pull request by skjnldsv**
```
 @nextcloud/axios          ^2.4.0  →  ^2.5.0
 @nextcloud/event-bus      ^3.1.0  →  ^3.3.1
 @nextcloud/files          ^3.0.0  →  ^3.9.0
 @nextcloud/initial-state  ^2.1.0  →  ^2.2.0
 @nextcloud/paths          ^2.1.0  →  ^2.2.1
```

### CODE REVIEW

**Comment by skjnldsv** [comment]
Cypress: `Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/`

**Comment by juliushaertl** [comment]
I can take over checking that

**Comment by skjnldsv** [comment]
Done @juliushaertl

**Review by juliushaertl — APPROVED** [review]

**Pull request merged**
