### PR TITLE
Add config option to turn on Collabora feature lock for read only users

### PR DESCRIPTION
**Pull request by juliushaertl**
Implementing the option to enable [feature locking](https://sdk.collaboraonline.com/docs/installation/Configuration.html?highlight=isuserlocked#feature-locking) for all users that are not within edit groups

Can be enabled with:

```
occ config:app:set richdocuments read_only_feature_lock --value=yes
```

### CODE REVIEW

**Review by julien-nc — COMMENTED** [review]
Looks good.

* What's the effect of enabling `IsUserLocked` in the file info?
* What's the use case of disabling `read_only_feature_lock`? Is it just to override admin settings?

**Comment by juliushaertl** [comment]
> What's the effect of enabling IsUserLocked in the file info?

Admins can limit functionality in the coolwsd.xml and configure a modal (e.g. for an upselling path at hosting providers)

> What's the use case of disabling read_only_feature_lock? Is it just to override admin settings?

By default it is disabled, when turned on every user that does not have edit permission will be considered locked with the above mentioned options from Collabora.

**Review by julien-nc — APPROVED** [review]
:+1:

**Pull request merged**
