### PR TITLE
allow to add ttf files

### PR DESCRIPTION
**Pull request by szaimen**
See https://github.com/nextcloud/server/blob/37bb33c5799b834dfef3fb73936bd0e5a4773fb8/resources/config/mimetypemapping.dist.json#L192

### CODE REVIEW

**Comment by szaimen** [comment]
BTW: it seems like the api used is unreliable:
image
See https://developer.mozilla.org/en-US/docs/Web/API/File/type

**Review by juliushaertl — APPROVED** [review]

**Comment by juliushaertl** [comment]
We could detect this on the server side by reading the file with https://github.com/nextcloud/server/blob/f5c361cf44739058b79f322576a1bad2d8c142d9/lib/private/Files/Type/Detection.php#L226 but let's get this in as it seems like a reasonable first step.

**Comment by szaimen** [comment]
> We could detect this on the server side by reading the file with https://github.com/nextcloud/server/blob/f5c361cf44739058b79f322576a1bad2d8c142d9/lib/private/Files/Type/Detection.php#L226 but let's get this in as it seems like a reasonable first step.

sounds good 👍

**Pull request merged**
