### PR TITLE
fix(Wopi): Mark sensitive parameter as such

### PR DESCRIPTION
**Pull request by nickvergessen**
Ref https://github.com/nextcloud/server/pull/39040
This is only effective in PHP 8.2+ but it's the better and our future approach so doing both in parallel

### CODE REVIEW

**Review by blizzz — CHANGES_REQUESTED** [review]
Also register via `IRegistrationContext::registerSensitiveMethods()` for PHP < 8.2.

**Comment by nickvergessen** [comment]
Hmm so that means https://github.com/nextcloud/server/pull/39040 is actually not needed anymore?

**Comment by blizzz** [comment]
> Hmm so that means [nextcloud/server#39040](https://github.com/nextcloud/server/pull/39040) is actually not needed anymore?

aye

**Review by blizzz — APPROVED** [review]

**Pull request merged**
