### PR TITLE
fix(Application.php): Update methods post-refactor

### PR DESCRIPTION
**Pull request by joshtrichards**
* Resolves: #3363
* Target version: main

### Summary

The refactor in #3315 swapped around a few methods and this updates Application.php to use the appropriate ones.

### Checklist

- [x] Code is properly formatted
- [x] Sign-off message is added to all commits
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Review by manuelkamp — APPROVED** [review]
this solved the issue

**Review by juliushaertl — APPROVED** [review]

**Comment by juliushaertl** [comment]
Thanks @joshtrichards 

I'm puzzled why psalm has not thrown an error for this case, but that is not a blocker for getting this in of course.

**Comment by gehkah** [comment]
The fix works for eliminating the errors. But It now hangs on uploading large files, like ISOs onto Nextcloud. Some instances crash. others just dont finalize the upload. I got NC instances where I did not apply this fix, there its working. on 3 instances, where I applied this fix, I got this problem. waiting on a new release.

**Comment by joshtrichards** [comment]
@gehkah Please open a bug report so that we can get the info needed to solve that. I'm afraid a mere comment on the original PR isn't sufficient to reproduce + fix the problem you're reporting (if it is, indeed, even related)

**Comment by gehkah** [comment]
> @gehkah Please open a bug report so that we can get the info needed to solve that. I'm afraid a mere comment on the original PR isn't sufficient to reproduce + fix the problem you're reporting (if it is, indeed, even related)

Dear Josh

I'm sorry for the circumstances. I upgraded to php8.3 and the problems are gone on my instances. I applied your fix to other NC instances and reproduces the problem unter php8.2 (VM, debian bullseye, apache2) but when I upgraded these to php 8.3, the problem no longer exists. No more 100% cpu usage or vm crash, I'm able to upload ISOs again. I'm fine with it. thank you very much!!

**Comment by prismopensource** [comment]
Same problem over here on PHP 8.2 problem was fixed by migrating to PHP 8.3.

**Pull request merged**
